let width = prompt("nhập rộng")
let height = prompt("nhập cao")
let rong = parseInt(width)
let cao = parseInt(height)
document.write('nhập chiều rộng ' + rong)
document.write('<br>')
document.write('nhập chiêu cao ' + cao)
document.write('<br>')
document.write('diện tích là ' + rong*cao)
